queue_rules:
  - name: default
    queue_conditions:
      - "base=master"
      - "label=merge me"
      - status-success=Haskell GHC 8.6.5 Test
      - status-success=Haskell GHC 8.8.4 Test
      - status-success=Haskell GHC 8.10.7 Test
      - status-success=Haskell GHC 9.0.1 Test
      - status-success=Haskell GHC 9.2.1 Test
    merge_conditions:
      - status-success=Haskell GHC 8.6.5 Test
      - status-success=Haskell GHC 8.8.4 Test
      - status-success=Haskell GHC 8.10.7 Test
      - status-success=Haskell GHC 9.0.1 Test
      - status-success=Haskell GHC 9.2.1 Test
    merge_method: squash

pull_request_rules:
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
