
queue_rules:
- name: default
  conditions:
  - status-success=Haskell GHC 8.6.5 Test
  - status-success=Haskell GHC 8.8.4 Test
  - status-success=Haskell GHC 8.10.7 Test
  - status-success=Haskell GHC 9.0.1 Test
  - status-success=Haskell GHC 9.2.1 Test

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "base=master"
      - "label=merge me"
      - status-success=Haskell GHC 8.6.5 Test
      - status-success=Haskell GHC 8.8.4 Test
      - status-success=Haskell GHC 8.10.7 Test
      - status-success=Haskell GHC 9.0.1 Test
      - status-success=Haskell GHC 9.2.1 Test
    actions:
      queue:
        method: squash
        name: default
