name: singletons-presburger
version: "0.6.1.0"
synopsis: Presburger Arithmetic Solver for GHC Type-level natural numbers with Singletons package.
description: |
  The @singletons-presburger@ plugin augments GHC type-system with Presburger
  Arithmetic Solver for Type-level natural numbers, with integration with <https://hackage.haskell.org/package/singletons singletons> package.

  You can use by adding this package to @dependencies@ and add the following pragma
  to the head of .hs files:

  > OPTIONS_GHC -fplugin Data.Singletons.TypeNats.Presburger
category: Math, Type System
author: Hiromi ISHII
maintainer: konn.jinro _at_ gmail.com
copyright: 2015 (c) Hiromi ISHII
license: BSD3
github: konn/ghc-typelits-presburger
tested-with: GHC==8.6.5 GHC==8.8.4 GHC==8.10.7 GHC==9.0.1 GHC==9.2.1
ghc-options:
  - -Wall
  - -Wno-dodgy-imports

when:
- condition: impl(ghc >= 9)
  then:
    dependencies:
    - singletons-base >= 3.0
    - singletons
    cpp-options:
    - -DSINGLETONS_BASE
  else:
    dependencies:
    - singletons
      
library:
  source-dirs:
    - src
  exposed-modules:
    - Data.Singletons.TypeNats.Presburger
  dependencies:
    - base >=4.7 && <5
    - ghc-typelits-presburger >= 0.4
    - mtl
    - reflection
executables:
  simple-arith:
    main: simple-arith.hs
    source-dirs: examples
    ghc-options:
      - -Wno-unused-imports
    dependencies:
      - base
      - singletons-presburger
      - equational-reasoning
    when:
    - condition: impl(ghc >= 9)
      then:
        dependencies:
        - singletons-base >= 3.0
        - singletons-th
        cpp-options:
        - -DSINGLETONS_BASE
      else:
        dependencies:
        - singletons
    - condition: ! "!(flag(examples))"
      buildable: false
flags:
  examples:
    description: Builds example
    manual: false
    default: false
