name: singletons-presburger
version: "0.7.3.0"
synopsis: Presburger Arithmetic Solver for GHC Type-level natural numbers with Singletons package.
description: |
  The @singletons-presburger@ plugin augments GHC type-system with Presburger
  Arithmetic Solver for Type-level natural numbers, with integration with <https://hackage.haskell.org/package/singletons singletons> package.

  You can use by adding this package to @dependencies@ and add the following pragma
  to the head of .hs files:

  > OPTIONS_GHC -fplugin Data.Singletons.TypeNats.Presburger
category: Math, Type System
extra-source-files:
- Changelog.md
author: Hiromi ISHII
maintainer: konn.jinro _at_ gmail.com
copyright: 2015 (c) Hiromi ISHII
license: BSD3
github: konn/ghc-typelits-presburger
tested-with: GHC==9.0.2 GHC==9.2.8 GHC==9.4.8 GHC==9.6.5 GHC==9.8.2 GHC==9.10.1
ghc-options:
  - -Wall
  - -Wno-dodgy-imports

dependencies:
- singletons-base >= 3.0
- singletons
cpp-options:
- -DSINGLETONS_BASE
      
library:
  source-dirs:
    - src
  exposed-modules:
    - Data.Singletons.TypeNats.Presburger
  dependencies:
    - base >=4.7 && <5
    - ghc-typelits-presburger >= 0.4
    - mtl
    - reflection
    - ghc
executables:
  simple-arith:
    main: simple-arith.hs
    source-dirs: examples
    ghc-options:
      - -Wno-unused-imports
    dependencies:
      - base
      - singletons-presburger
      - equational-reasoning
      - singletons-base >= 3.0
      - singletons-th
    when:
    - condition: ! "!(flag(examples))"
      buildable: false
flags:
  examples:
    description: Builds example
    manual: false
    default: false
