name: ghc-typelits-presburger
version: "0.6.2.0"
synopsis: Presburger Arithmetic Solver for GHC Type-level natural numbers.
description: |
  @ghc-typelits-presburger@ augments GHC type-system with Presburger
  Arithmetic Solver for Type-level natural numbers.
  This plugin only work with GHC builtin operations.
  To work with those of @singletons@ package, use @ghc-typelits-meta@ and/or @ghc-typelits-presburger@ instead.

  Since 0.3.0.0, integration with <https://hackage.haskell.org/package/singletons singletons> package moves to <https://hackage.haskell.org/package/singletons-presburger singletons-presburger>.

  You can use by adding this package to @build-depends@ and add the following pragma
  to the head of .hs files:


  > OPTIONS_GHC -fplugin GHC.TypeLits.Presburger
category: Math, Type System
author: Hiromi ISHII
maintainer: konn.jinro _at_ gmail.com
copyright: 2015 (c) Hiromi ISHII
license: BSD3
github: konn/ghc-typelits-presburger
tested-with: GHC==8.6.5 GHC==8.8.4 GHC==8.10.7 GHC==9.0.1 GHC==9.2.1
ghc-options:
  - -Wall
  - -Wno-dodgy-imports

dependencies:
- base

library:
  source-dirs:
    - src
  exposed-modules:
    - GHC.TypeLits.Presburger.Types
    - GHC.TypeLits.Presburger
    - GHC.TypeLits.Presburger.Compat
  dependencies:
    - base >=4.7 && <5
    - containers
    - ghc-tcplugins-extra >=0.2 && <0.5
    - mtl
    - pretty
    - reflection
    - syb
    - transformers
    - ghc < 9.3
executables:
  simple-arith-core:
    main: simple-arith-core.hs
    source-dirs: examples
    ghc-options:
      - -Wno-unused-imports
    dependencies:
      - base
      - ghc-typelits-presburger
      - equational-reasoning
    when:
      - condition: ! "!(flag(examples))"
        buildable: false
flags:
  examples:
    description: Builds example
    manual: false
    default: false

tests:
  test-typeltis-presburger:
    source-dirs: test
    main: test.hs
    build-tools:
    - tasty-discover
    dependencies:
    - ghc-typelits-presburger
    - equational-reasoning
    - tasty
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - text
