name: Haskell CI

on:
  push:
    branches: 
    - master
    - release
  pull_request:
    branches:
    - master
    - release

jobs:
  enumerate:
    name: Generate Build Matrix Dynamically
    runs-on: ubuntu-latest
    outputs:
      configs: ${{ steps.enumerate.outputs.configs }}
    steps:
    - uses: actions/checkout@v3
    - name: Enumerate Configs
      id: enumerate
      run: |
        set -euxo pipefail
        find ci-configs/ -type f -name 'ghc-*.config' \
          | sort -h | jq -ncR '[inputs | {ghc:  match("ghc-(.+)\\.config$", .) | .captures[0].string | select(.), plan: .}]' | tee configs.json
        echo "configs=$(cat configs.json)" >> "${GITHUB_OUTPUT}"

  build:
    needs: [enumerate]
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJSON(needs.enumerate.outputs.configs)}}
    runs-on: ubuntu-latest
    name: Haskell GHC ${{ matrix.ghc }} Build
    env:
      CABAL: cabal --project-file=${{matrix.plan}}

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 3.10.1.0
        enable-stack: false

    - name: Cache ~/.cabal/store
      uses: actions/cache@v2
      env:
        cache-name: cache-cabal-store
      with:
        path: ~/.cabal/store
        key: build-${{ runner.os }}-${{env.cache-name}}-${{matrix.ghc}}-${{ hashFiles('**/*.cabal', '${{matrix.plan}}') }}
        restore-keys: |
          build-${{ runner.os }}-${{env.cache-name}}-${{matrix.ghc}}-

    - name: Cache dist-newstyle
      uses: actions/cache@v2
      env:
        cache-name: cache-dist-newstyle
      with:
        path: dist-newstyle
        key: build-${{ runner.os }}-${{ env.cache-name }}-${{matrix.ghc}}-${{ hashFiles('**/*.cabal', '${{matrix.plan}}') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          build-${{ runner.os }}-${{ env.cache-name }}-${{matrix.ghc}}-${{ hashFiles('**/*.cabal', '${{matrix.plan}}') }}-
          build-${{ runner.os }}-${{ env.cache-name }}-${{matrix.ghc}}-

    - name: Configure and Update
      run: >-
        ${CABAL} v2-configure
        --enable-tests --enable-benchmarks
        --constraint "singletons-presburger +examples"
        --constraint "ghc-typelits-presburger +examples"

        ${CABAL} v2-update
    - name: Build
      run: |
        ${CABAL} v2-build
    - name: Collect binaries
      run: ./ci-scripts/collect-artifacts.sh artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: artifacts

  test:
    needs:
    - enumerate
    - build
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJSON(needs.enumerate.outputs.configs)}}

    runs-on: ubuntu-latest
    name: Haskell GHC ${{ matrix.ghc }} Test
    env:
      STACK_YAML: stack-${{matrix.ghc}}.yaml

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      id: download
    - run: |
        set -euxo pipefail
        DL_PATH=${{steps.download.outputs.download-path}}
        echo "${DL_PATH}"
        ls -R "${DL_PATH}"
        exit 1
